# Generated by Django 5.1.7 on 2025-03-23 21:55

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Дата создания')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Отменена')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hikes.hike', verbose_name='Поход')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
