# Generated by Django 5.1.7 on 2025-03-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название похода')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время похода')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hikes/', verbose_name='Фото')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
    ]
