# Generated by Django 5.1.7 on 2025-03-26 12:17

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='start_at',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now(), verbose_name='Дата и время похода'),
        ),
    ]
