# Generated by Django 5.1.7 on 2025-03-28 15:00

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0002_alter_hike_start_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hike',
            options={'ordering': ['start_at']},
        ),
        migrations.AlterField(
            model_name='hike',
            name='start_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Дата и время похода'),
        ),
    ]
