# Generated by Django 5.1.7 on 2025-03-27 16:53

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_initial_user(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')

    if not CustomUser.objects.filter(email='admin@admin.ru').exists():
        CustomUser.objects.create(
            first_name='Admin',
            last_name='Adminov',
            email='admin@admin.ru',
            password=make_password('admin'),
            is_active=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_user)
    ]
